spring.application.name=StatelessSpringSecurityDemo
spring.security.oauth2.client.registration.keycloak.client-id=my-client
spring.security.oauth2.client.registration.keycloak.client-secret=5luQPhilh8VbEjrLF7pr2rkjak7BA8EJ
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/myrealm
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
server.servlet.session.persistent=false
server.servlet.session.cookie.http-only=true
server.servlet.session.tracking-modes=
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.security.web.session=TRACE
logging.level.org.springframework.security.web.context=TRACE
logging.level.org.springframework.security.web.authentication.session=TRACE




